### ISSUE TITLE
Ability to download content by its name, rather than its tag

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/pr-downloader#19]
e.g. instead of `./pr-downloader.exe --download-game byar:git:fff9e7afdb0f45378eadef107c9e5156ae3d32ef`, I would like to be able to do `./pr-downloader.exe --download-game "Beyond All Reason test-16314-fff9e7a"`.

This would save the lobby from having to its own version lookup.

**Comment by p2004a** [comment]
@Jazcash this already works. Try it.

The one issue is that it's a bit less efficient then downloading by tag. I have a branch (https://github.com/beyond-all-reason/pr-downloader/compare/master...p2004a:pr-downloader:parallel-game-download) that makes it better, and on CDN with few repos then on main spring hosting it's going to be even better, but it's still not as efficient.

Theoretically this could be solved by another argument like "repos whitelist", but that would be IMHO a separate issue from this one.

So: please test it, as it works for me.

**Comment by Jazcash** [comment]
lol so it does, didn't see it anywhere in the doc, guess I should've just tried it first 😅
