### ISSUE TITLE
Can't build pr-d under MSVC

### ISSUE THREAD

**Issue by lhog** [beyond-all-reason/pr-downloader#30]
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'getopt.h': No such file or directory	pr-downloader	C:\spring\tools\pr-downloader\src\main.cpp	13	
```

**Comment by p2004a** [comment]
Started looking into it once I've set up compiler aaand there is a bunch of places where indeed posix only functionality is used.

**Comment by p2004a** [comment]
Aaand done, compilation under MSVC works, and all the current functional test we have for prd pass on that build (we don't have 100% coverage for functionality yet though)
